/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/ImgurPlugin.ts
var ImgurPlugin_exports = {};
__export(ImgurPlugin_exports, {
  default: () => ImgurPlugin
});
module.exports = __toCommonJS(ImgurPlugin_exports);
var import_obsidian7 = require("obsidian");

// src/UploadStrategy.ts
var _UploadStrategy = class _UploadStrategy {
  constructor(id, description) {
    this.id = id;
    this.description = description;
    _UploadStrategy.valuesArr.push(this);
  }
  static get values() {
    return this.valuesArr;
  }
};
_UploadStrategy.valuesArr = [];
_UploadStrategy.ANONYMOUS_IMGUR = new _UploadStrategy("ANONYMOUS_IMGUR", "Anonymous Imgur upload");
_UploadStrategy.AUTHENTICATED_IMGUR = new _UploadStrategy(
  "AUTHENTICATED_IMGUR",
  "Authenticated Imgur upload"
);
var UploadStrategy = _UploadStrategy;

// src/imgur/constants.ts
var IMGUR_API_BASE = "https://api.imgur.com/3";
var IMGUR_ACCESS_TOKEN_LOCALSTORAGE_KEY = "imgur-access_token";

// src/uploader/ApiError.ts
var ApiError = class extends Error {
};

// src/imgur/AuthenticatedImgurClient.ts
var import_obsidian = require("obsidian");

// src/utils/multipart-http.ts
function buildMultipartBody(formData, boundary) {
  const multipartPirces = multipartPiecesFrom(formData);
  return composeMultipartBodyFrom(multipartPirces, boundary);
}
function multipartPiecesFrom(formData) {
  const pieces = [];
  formData.forEach((content, name) => {
    if (typeof content === "string") {
      pieces.push(stringToFormDataSection(name, content));
    } else if (content instanceof File) {
      pieces.push(fileToFormDataSection(name, content));
    }
  });
  return pieces;
}
var MIME_LINE_BREAK = "\r\n";
var DOUBLE_LINE_BREAK = `${MIME_LINE_BREAK}${MIME_LINE_BREAK}`;
function stringToFormDataSection(formName, strValue) {
  return `Content-Disposition: form-data; name="${formName}"${DOUBLE_LINE_BREAK}${strValue}`;
}
function fileToFormDataSection(formName, file) {
  const firstLine = `Content-Disposition: form-data; name="${formName}"; filename="${file.name}"`;
  const contentType = file.type ? [MIME_LINE_BREAK, `Content-Type: ${file.type}`] : [""];
  return new Blob([firstLine, ...contentType, DOUBLE_LINE_BREAK, file]);
}
function composeMultipartBodyFrom(multipartPieces, boundaryLine) {
  const allPieces = addMultipartBoundaries(multipartPieces, boundaryLine);
  const singleBlob = new Blob(addLineBreaks(allPieces));
  return singleBlob;
}
function addMultipartBoundaries(multipartPieces, boundary) {
  const boundaryLine = `--${boundary}`;
  const allPieces = multipartPieces.flatMap((p) => [boundaryLine, p]);
  const finalBoundaryLine = `--${boundary}--`;
  allPieces.push(finalBoundaryLine);
  return allPieces;
}
function addLineBreaks(allPieces) {
  const result = [];
  for (let i = 0; i < allPieces.length; i++) {
    result.push(allPieces[i]);
    if (i !== allPieces.length - 1) {
      result.push(MIME_LINE_BREAK);
    }
  }
  return result;
}

// src/utils/obsidian-http-client.ts
async function prepareMultipartRequestPiece(requestData) {
  const boundary = `----formdata-0${`${Math.floor(Math.random() * 1e11)}`.padStart(11, "0")}`;
  return {
    contentType: `multipart/form-data; boundary=${boundary}`,
    body: await buildMultipartBody(requestData, boundary).arrayBuffer()
  };
}

// src/imgur/AuthenticatedImgurClient.ts
function handleImgurErrorResponse(resp) {
  if (resp.headers["Content-Type"] === "application/json") {
    throw new ApiError(resp.json.data.error);
  }
  throw new Error(resp.text);
}
var AuthenticatedImgurClient = class {
  constructor(accessToken) {
    this.accessToken = accessToken;
    void this.accountInfo().then((r) => this.authenticatedUser = r.data.url).catch((e) => console.error("Failed to get info about currently authenticated user!", e));
  }
  async accountInfo() {
    const req = {
      url: `${IMGUR_API_BASE}/account/me`,
      method: "GET",
      headers: { Authorization: `Bearer ${this.accessToken}` },
      throw: false
    };
    const resp = await (0, import_obsidian.requestUrl)(req);
    if (resp.status >= 400) {
      handleImgurErrorResponse(resp);
    }
    return resp.json;
  }
  async upload(image, albumId) {
    const requestData = new FormData();
    requestData.append("image", image);
    if (albumId) {
      requestData.append("album", albumId);
    }
    const request = {
      url: `${IMGUR_API_BASE}/image`,
      method: "POST",
      headers: { Authorization: `Bearer ${this.accessToken}` },
      ...await prepareMultipartRequestPiece(requestData),
      throw: false
    };
    const resp = await (0, import_obsidian.requestUrl)(request);
    if (resp.status >= 400) {
      handleImgurErrorResponse(resp);
    }
    return resp.json;
  }
  async listAlbums() {
    const req = {
      url: `${IMGUR_API_BASE}/account/${this.authenticatedUser}/albums`,
      method: "GET",
      headers: { Authorization: `Bearer ${this.accessToken}` },
      throw: false
    };
    const resp = await (0, import_obsidian.requestUrl)(req);
    if (resp.status >= 400) {
      handleImgurErrorResponse(resp);
    }
    return resp.json;
  }
  async createNewAlbum(name, description) {
    const requestData = new FormData();
    requestData.append("title", name);
    if (description) {
      requestData.append("description", description);
    }
    const request = {
      url: `${IMGUR_API_BASE}/album`,
      method: "POST",
      headers: { Authorization: `Bearer ${this.accessToken}` },
      ...await prepareMultipartRequestPiece(requestData),
      throw: false
    };
    const resp = await (0, import_obsidian.requestUrl)(request);
    if (resp.status >= 400) {
      handleImgurErrorResponse(resp);
    }
    return resp.json;
  }
};

// src/uploader/imgur/ImgurAnonymousUploader.ts
var import_obsidian2 = require("obsidian");
var ImgurAnonymousUploader = class {
  constructor(clientId) {
    this.clientId = clientId;
  }
  async upload(image) {
    const requestData = new FormData();
    requestData.append("image", image);
    const request = {
      url: `${IMGUR_API_BASE}/image`,
      method: "POST",
      headers: { Authorization: `Client-ID ${this.clientId}` },
      ...await prepareMultipartRequestPiece(requestData),
      throw: false
    };
    const resp = await (0, import_obsidian2.requestUrl)(request);
    if (resp.status >= 400) {
      handleImgurErrorResponse(resp);
    }
    return resp.json.data.link;
  }
};

// src/uploader/imgur/ImgurAuthenticatedUploader.ts
var ImgurAuthenticatedUploader = class {
  constructor(client) {
    this.client = client;
  }
  async upload(image, albumId) {
    return (await this.client.upload(image, albumId)).data.link;
  }
};

// src/uploader/imgUploaderFactory.ts
function buildUploaderFrom(settings) {
  if (UploadStrategy.AUTHENTICATED_IMGUR.id === settings.uploadStrategy) {
    const accessToken = localStorage.getItem(IMGUR_ACCESS_TOKEN_LOCALSTORAGE_KEY);
    if (!accessToken) {
      return void 0;
    }
    return new ImgurAuthenticatedUploader(new AuthenticatedImgurClient(accessToken));
  }
  if (settings.uploadStrategy === UploadStrategy.ANONYMOUS_IMGUR.id) {
    if (settings.clientId) {
      return new ImgurAnonymousUploader(settings.clientId);
    } else {
      return void 0;
    }
  }
  throw Error("This line of code should never be reached");
}

// src/utils/misc.ts
function fixImageTypeIfNeeded(image) {
  if (passesInstanceofCheck(image)) {
    return image;
  }
  return new File([image], image.name, { type: image.type, lastModified: image.lastModified });
  function passesInstanceofCheck(image2) {
    return image2 instanceof File;
  }
}

// src/ui/ImgurPluginSettingsTab.ts
var import_obsidian6 = require("obsidian");

// src/ui/ImgurAuthModal.ts
var import_obsidian3 = require("obsidian");
var ONE_SECOND_MILLIS = 1e3;
var OPEN_BROWSER_IN_SECONDS = 4;
var ImgurAuthModal = class extends import_obsidian3.Modal {
  constructor(clientId, app, afterClose) {
    super(app);
    this.afterClose = afterClose;
    this.secondsLeft = OPEN_BROWSER_IN_SECONDS;
    this.opened = false;
    this.intervalId = null;
    this.authLink = `https://api.imgur.com/oauth2/authorize?client_id=${clientId}&response_type=token`;
  }
  get isOpen() {
    return this.opened;
  }
  onOpen() {
    this.opened = true;
    this.timerDiv = this.modalEl.createDiv();
    this.updateText();
    this.intervalId = window.setInterval(() => {
      this.secondsLeft -= 1;
      this.updateText();
      if (this.secondsLeft === 0) {
        window.open(this.authLink);
        if (this.intervalId !== null) {
          clearInterval(this.intervalId);
        }
      }
    }, ONE_SECOND_MILLIS);
    this.addNoWaitDiv(this.intervalId);
    new import_obsidian3.ButtonComponent(this.modalEl.createDiv()).setButtonText("Cancel").setCta().onClick(() => this.close());
  }
  onClose() {
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
    }
    this.opened = false;
    if (this.afterClose) void this.afterClose();
  }
  addNoWaitDiv(interval) {
    const linkEl = createEl("a", { href: this.authLink, text: "here" });
    const noWaitDiv = this.modalEl.createDiv();
    noWaitDiv.appendText("If you do not want to wait, click ");
    noWaitDiv.append(linkEl);
    linkEl.onclick = () => {
      clearInterval(interval);
      this.secondsLeft = 0;
      this.updateText();
    };
    return noWaitDiv;
  }
  updateText() {
    this.timerDiv.setText(
      `Please complete authentication at imgur.com; Opening browser in ${this.secondsLeft} seconds...`
    );
  }
};

// src/ui/ImgurAuthenticationStatus.ts
var import_obsidian4 = require("obsidian");
var ImgurAuthenticationStatus = class {
  constructor(parent) {
    this.parent = parent;
    const settingItem = this.parent.createDiv();
    settingItem.addClass("setting-item");
    const settingItemInfo = settingItem.createDiv();
    settingItemInfo.addClass("setting-item-info");
    const settingItemControl = settingItem.createDiv();
    settingItemControl.addClass("setting-item-control");
    this.authStatusDiv = settingItemInfo.createDiv();
    this.buttonsDiv = settingItemControl;
  }
  setNotAuthenticated() {
    this.clear();
    this.authStatusDiv.setText("Not authenticated");
    this.addAuthButton();
  }
  setStatusChecking() {
    this.clear();
    this.authStatusDiv.setText("Checking Imgur authentication...");
  }
  setAuthenticatedAs(currentUser) {
    this.clear();
    this.authStatusDiv.setText(`Authenticated as: ${currentUser} \u2705`);
    this.addLogoutButton();
  }
  setInternetConnectionProblem() {
    this.clear();
    this.authStatusDiv.setText("Internet connection problem");
  }
  setImgurSessionError(sessionError) {
    this.clear();
    this.authStatusDiv.setText(`Imgur session error: ${sessionError}`);
    this.addAuthButton();
  }
  setNotAuthenticatedWithError() {
    this.clear();
    this.authStatusDiv.setText("\u26A0\uFE0F Not authenticated. See console for error");
    this.addAuthButton();
  }
  disableAuthButton() {
    var _a;
    (_a = this.authButton) == null ? void 0 : _a.setDisabled(true);
  }
  enableAuthButton() {
    var _a;
    (_a = this.authButton) == null ? void 0 : _a.setDisabled(false);
  }
  clear() {
    this.authStatusDiv.empty();
    this.buttonsDiv.empty();
    this.authButton = void 0;
  }
  addLogoutButton() {
    new import_obsidian4.ButtonComponent(this.buttonsDiv).setButtonText("Logout").setWarning().onClick((e) => this.logoutButtonClick(e));
  }
  addAuthButton() {
    this.authButton = new import_obsidian4.ButtonComponent(this.buttonsDiv).setButtonText("Authenticate").setCta().onClick((e) => this.authButtonClick(e));
  }
};

// src/ui/NewAlbumModal.ts
var import_obsidian5 = require("obsidian");
var NewAlbumModal = class extends import_obsidian5.Modal {
  onOpen() {
    this.setModalTitle();
    const { newAlbumNameField, newAlbumDescriptionField } = this.createInputs();
    const { createButton, cancelButton } = this.createButtons();
    setRequiredAlbumNameChangeCallback(newAlbumNameField, createButton);
    this.setCreateButtonCallback(createButton, newAlbumNameField, newAlbumDescriptionField);
    cancelButton.onClick(() => this.close());
  }
  setModalTitle() {
    this.titleEl.setText("Create new album");
  }
  createInputs() {
    const newAlbumNameField = new import_obsidian5.TextComponent(
      this.modalEl.createDiv("setting-item").createDiv("setting-item-info")
    );
    newAlbumNameField.setPlaceholder("Album name (required)");
    newAlbumNameField.inputEl.setAttr("maxlength", 55);
    newAlbumNameField.inputEl.setCssStyles({ width: "100%" });
    const newAlbumDescriptionField = new import_obsidian5.TextAreaComponent(
      this.modalEl.createDiv("setting-item").createDiv("setting-item-info")
    );
    newAlbumDescriptionField.setPlaceholder("Album description (optional)");
    newAlbumDescriptionField.inputEl.setCssStyles({ width: "100%" });
    return { newAlbumNameField, newAlbumDescriptionField };
  }
  createButtons() {
    const buttonsContainer = this.modalEl.createDiv("modal-button-container");
    const cancelButton = new import_obsidian5.ButtonComponent(buttonsContainer);
    cancelButton.setButtonText("Cancel");
    const createButton = new import_obsidian5.ButtonComponent(buttonsContainer);
    createButton.setButtonText("Create");
    disableActionButton(createButton);
    return { createButton, cancelButton };
  }
  setCreateButtonCallback(createButton, albumNameField, albumDescriptionField) {
    createButton.onClick(async () => {
      setButtonInProgress(createButton);
      await this.createButtonHandler(albumNameField.getValue(), albumDescriptionField.getValue());
      this.close();
    });
  }
};
function setRequiredAlbumNameChangeCallback(newAlbumNameField, createButton) {
  newAlbumNameField.onChange((value) => {
    if (value.length === 0) {
      disableActionButton(createButton);
    } else {
      activateActionButton(createButton);
    }
  });
}
function setButtonInProgress(createButton) {
  createButton.setDisabled(true);
  createButton.setIcon("loader");
}
function activateActionButton(createButton) {
  createButton.setDisabled(false);
  createButton.setCta();
}
function disableActionButton(button) {
  button.setDisabled(true);
  button.buttonEl.setAttribute("disabled", "true");
  button.removeCta();
}

// src/ui/ImgurPluginSettingsTab.ts
var ImgurPluginSettingsTab = class _ImgurPluginSettingsTab extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.authenticatedUserName = void 0;
    this.plugin = plugin;
    this.strategyDiv = createDiv();
    this.plugin.registerEvent(
      this.app.workspace.on("layout-change", () => {
        const url = new URL(window.location.href);
        const hash = url.hash.slice(1);
        if (hash.includes("access_token")) {
          this.handleOAuthCallback({ hash });
        }
      })
    );
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Imgur Plugin settings" });
    const uploadApproachDiv = containerEl.createDiv();
    containerEl.appendChild(this.strategyDiv);
    new import_obsidian6.Setting(uploadApproachDiv).setName("Images upload approach").addDropdown((dropdown) => {
      UploadStrategy.values.forEach((s) => {
        dropdown.addOption(s.id, s.description);
      });
      dropdown.setValue(this.plugin.settings.uploadStrategy);
      dropdown.onChange(async (v) => {
        this.plugin.settings.uploadStrategy = v;
        await this.plugin.saveSettings();
        this.plugin.setupImagesUploader();
        await this.drawSettings();
      });
    });
    void this.drawSettings();
    new import_obsidian6.Setting(containerEl).setName("Confirm before upload").addToggle((t) => {
      t.setValue(this.plugin.settings.showRemoteUploadConfirmation);
      t.onChange(async (newValue) => {
        this.plugin.settings.showRemoteUploadConfirmation = newValue;
        await this.plugin.saveSettings();
      });
    });
  }
  handleOAuthCallback(params) {
    if (!this.authModal || !this.authModal.isOpen) return;
    if (params.error && typeof params.error === "string") {
      new import_obsidian6.Notice(`Authentication failed with error: ${params.error}`);
      return;
    }
    if (typeof params.hash === "string") {
      const mappedData = params.hash.split("&").map((p) => {
        const sp = p.split("=");
        return [sp[0], sp[1]];
      });
      const map = new Map(mappedData);
      const accessToken = map.get("access_token");
      if (accessToken) {
        localStorage.setItem(IMGUR_ACCESS_TOKEN_LOCALSTORAGE_KEY, accessToken);
      }
      this.plugin.setupImagesUploader();
      this.authModal.close();
      this.authModal = void 0;
    }
  }
  async hide() {
    await this.plugin.saveSettings();
    this.plugin.setupImagesUploader();
  }
  async drawSettings() {
    this.strategyDiv.empty();
    this.drawClientIdField(this.strategyDiv);
    if (this.plugin.settings.uploadStrategy === UploadStrategy.AUTHENTICATED_IMGUR.id) {
      await this.createAuthenticationInfoBlock(this.strategyDiv);
      if (this.authenticatedUserName) {
        this.drawAlbumSettings(this.strategyDiv);
      }
    }
  }
  drawClientIdField(containerEl) {
    new import_obsidian6.Setting(containerEl).setName("Client ID").setTooltip(`Personal Client ID is required for plugin to work`, { delay: 1 }).setDesc(_ImgurPluginSettingsTab.clientIdSettingDescription()).addText(
      (text) => text.setPlaceholder("Enter your client_id").setValue(this.plugin.settings.clientId).onChange(async (value) => {
        this.plugin.settings.clientId = value;
        await this.plugin.saveSettings();
        this.enableOrDisableAuthenticationButton();
      })
    );
  }
  static clientIdSettingDescription() {
    const fragment = document.createDocumentFragment();
    const newClientIdInstructionsLink = document.createElement("a");
    newClientIdInstructionsLink.textContent = "the instructions";
    newClientIdInstructionsLink.setAttribute(
      "href",
      "https://github.com/gavvvr/obsidian-imgur-plugin?tab=readme-ov-file#generating-client-id"
    );
    const existingClientIdsLink = document.createElement("a");
    existingClientIdsLink.text = "here";
    existingClientIdsLink.setAttribute("href", "https://imgur.com/account/settings/apps");
    fragment.append("Find your existing Client ID ", existingClientIdsLink);
    fragment.append(" or follow ", newClientIdInstructionsLink, " to generate new Client ID.");
    return fragment;
  }
  enableOrDisableAuthenticationButton() {
    if (this.authElem) {
      if (this.plugin.settings.clientId) {
        this.authElem.enableAuthButton();
      } else {
        this.authElem.disableAuthButton();
      }
    }
  }
  async createAuthenticationInfoBlock(parentEl) {
    this.authElem = new ImgurAuthenticationStatus(parentEl);
    await this.drawAuthenticationInfo();
    this.enableOrDisableAuthenticationButton();
    this.authElem.authButtonClick = () => {
      const modal = new ImgurAuthModal(this.plugin.settings.clientId, this.app, async () => {
        await this.drawAuthenticationInfo();
      });
      modal.open();
      this.authModal = modal;
    };
    this.authElem.logoutButtonClick = async () => {
      localStorage.removeItem(IMGUR_ACCESS_TOKEN_LOCALSTORAGE_KEY);
      this.plugin.setupImagesUploader();
      await this.drawAuthenticationInfo();
    };
  }
  async drawAuthenticationInfo() {
    const authenticatedClient = this.plugin.getAuthenticatedImgurClient();
    if (!authenticatedClient || !this.authElem) {
      if (this.authElem) {
        this.authElem.setNotAuthenticated();
      }
      return;
    }
    this.authElem.setStatusChecking();
    try {
      const accountInfo = await authenticatedClient.accountInfo();
      this.authenticatedUserName = accountInfo.data.url;
      this.authElem.setAuthenticatedAs(this.authenticatedUserName || "");
    } catch (e) {
      if (e instanceof TypeError && e.message === "Failed to fetch") {
        this.authElem.setInternetConnectionProblem();
      } else if (e instanceof ApiError) {
        this.authElem.setImgurSessionError(e.message);
      } else {
        console.warn("Not authenticated, exception: ", e);
        this.authElem.setNotAuthenticatedWithError();
      }
    }
  }
  drawAlbumSettings(parentEl) {
    const albumSetting = new import_obsidian6.Setting(parentEl);
    if (this.authenticatedUserName) {
      this.addAlbumsManagerLink(albumSetting.descEl, this.authenticatedUserName);
    }
    albumSetting.setName("Album to upload").addDropdown(async (d) => {
      var _a;
      d.setDisabled(true);
      d.addOption("", "Loading...");
      await this.populateList(d);
      (_a = d.selectEl.options[0]) == null ? void 0 : _a.remove();
      d.setDisabled(false);
      d.onChange(async (value) => {
        if (value === "\uFF0B") {
          const handler = async (name, description) => {
            const client = this.plugin.getAuthenticatedImgurClient();
            if (client) {
              try {
                const resp = await client.createNewAlbum(name, description);
                if (resp.success === true) {
                  await this.populateList(d);
                  d.setValue(resp.data.id);
                  d.selectEl.removeClass("mod-warning");
                  this.plugin.settings.albumToUpload = resp.data.id;
                  await this.plugin.saveSettings();
                }
              } catch (e) {
                new import_obsidian6.Notice("Failed to create new album. Open console to see log");
                console.error("Failed to create a new album", e);
              }
            }
          };
          const modal = new NewAlbumModal(this.app);
          modal.createButtonHandler = handler;
          modal.open();
          return;
        }
        if (value === "null") {
          this.plugin.settings.albumToUpload = void 0;
        } else {
          this.plugin.settings.albumToUpload = value;
        }
        await this.plugin.saveSettings();
        Array.from(d.selectEl.options).forEach((opt) => {
          if (opt.value === value) {
            if (opt.innerText.includes("\u26A0\uFE0F")) {
              d.selectEl.addClass("mod-warning");
            } else {
              d.selectEl.removeClass("mod-warning");
            }
          }
        });
      });
    });
  }
  addAlbumsManagerLink(element, loggedInUser) {
    const link = `https://${loggedInUser}.imgur.com/all`;
    const linkEl = createEl("a", { href: link, text: link });
    element.appendText("Manage your albums at ");
    element.append(linkEl);
  }
  async populateList(d) {
    const client = this.plugin.getAuthenticatedImgurClient();
    if (client) {
      const albums = (await client.listAlbums()).data;
      albums.sort((a1, a2) => a1.datetime - a2.datetime);
      d.addOption("null", "Not specified");
      d.addOption("\uFF0B", "\uFF0B Create new album");
      for (const album of albums) {
        d.addOption(album.id, album.title);
      }
      const currentlyChosenAlbum = this.plugin.settings.albumToUpload;
      if (currentlyChosenAlbum != void 0 && !albums.some((a) => a.id === currentlyChosenAlbum)) {
        d.addOption(
          currentlyChosenAlbum,
          `id: ${currentlyChosenAlbum} (\u26A0\uFE0F album not found at imgur.com)`
        );
        d.selectEl.addClass("mod-warning");
      }
      d.setValue(currentlyChosenAlbum != null ? currentlyChosenAlbum : "null");
    }
  }
};

// src/ImgurPlugin.ts
var DEFAULT_SETTINGS = {
  uploadStrategy: UploadStrategy.ANONYMOUS_IMGUR.id,
  clientId: "",
  showRemoteUploadConfirmation: true,
  albumToUpload: void 0
};
var ImgurPlugin = class extends import_obsidian7.Plugin {
  onload() {
    this.loadSettings().then(() => {
      this.addSettingTab(new ImgurPluginSettingsTab(this.app, this));
      this.setupImagesUploader();
      this.setupImgurHandlers();
      this.addResizingCommands();
    }).catch(console.error);
  }
  getCurrentImagesUploader() {
    return this.imgUploaderField;
  }
  getAuthenticatedImgurClient() {
    if (this.imgUploaderField instanceof ImgurAuthenticatedUploader) {
      return this.imgUploaderField.client;
    }
    return null;
  }
  setupImagesUploader() {
    const uploader = buildUploaderFrom(this.settings);
    if (!uploader) {
      this.imgUploaderField = {
        upload: () => Promise.reject(new Error("Uploader not initialized"))
      };
      return;
    }
    this.imgUploaderField = uploader;
    const originalUploadFunction = uploader.upload.bind(uploader);
    uploader.upload = (image, albumId) => {
      return originalUploadFunction(fixImageTypeIfNeeded(image), albumId);
    };
  }
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS, ...loadedData };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  setupImgurHandlers() {
  }
  addResizingCommands() {
  }
};
